application: twistedr-deseret
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: assets/js
- url: /css
  static_dir: assets/css
- url: /fonts
  static_dir: assets/fonts
- url: /images
  static_dir: assets/images
- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

inbound_services:
- warmup